/* Generated by tools/vendor/patch-for-r.sh -- do not edit by hand. */
#ifndef ZUSAT_R_COMPAT_H
#define ZUSAT_R_COMPAT_H

/* R_NO_REMAP keeps R from defining `error`, `length` and friends as macros,
   which would collide with CaDiCaL's own names across 90 files. These two
   headers are the narrow ones: they declare Rprintf/REprintf/Rvprintf/
   REvprintf and Rf_error and little else. R's real declarations are used
   rather than hand-written prototypes so the calling convention -- and
   dllimport on Windows -- always matches whatever R we build against. */
#ifndef R_NO_REMAP
#define R_NO_REMAP
#endif

#include <R_ext/Print.h>
#include <R_ext/Error.h>

/* CaDiCaL calls abort()/exit() on internal errors and invalid API use.
   Both would take R's process down with them, so they raise an R condition
   instead. This unwinds through C++ frames without running destructors --
   acceptable only because it is already a non-recoverable path. */
#define ZUSAT_FATAL(what) \
  Rf_error ("CaDiCaL %s (%s:%d)", what, __FILE__, __LINE__)

#endif /* ZUSAT_R_COMPAT_H */
