#!/bin/sh
# Vendor CaDiCaL into src/cadical/. Re-run to upgrade.
#
# Usage: tools/vendor-cadical.sh [git-ref]
set -eu

REF="${1:-rel-3.0.1}"
REPO="https://github.com/arminbiere/cadical.git"
PKG_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$PKG_ROOT/src/cadical"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "Cloning $REPO at $REF ..."
git clone --quiet --depth 1 --branch "$REF" "$REPO" "$TMP/cadical" 2>/dev/null \
  || { git clone --quiet "$REPO" "$TMP/cadical"; git -C "$TMP/cadical" checkout --quiet "$REF"; }

VERSION="$(cat "$TMP/cadical/VERSION")"
COMMIT="$(git -C "$TMP/cadical" rev-parse HEAD)"

rm -rf "$DEST"
mkdir -p "$DEST"
cp "$TMP"/cadical/src/*.cpp "$TMP"/cadical/src/*.hpp \
   "$TMP"/cadical/src/*.c   "$TMP"/cadical/src/*.h   "$DEST/"

# Drop files that define main() or export competing solver ABIs.
#   cadical.cpp / mobical.cpp -> main()
#   ipasir.cpp                -> IPASIR symbols we do not want in the .so
rm -f "$DEST/cadical.cpp" "$DEST/mobical.cpp" "$DEST/ipasir.cpp" "$DEST/ipasir.h"

cp "$TMP/cadical/LICENSE" "$PKG_ROOT/inst/CADICAL_LICENSE"

# Adapt the tree to R's C API (output, fatal paths, no fork/exec) before
# anything is recorded, so checksums cover exactly what gets compiled.
( cd "$PKG_ROOT" && ./tools/vendor/patch-for-r.sh )

# R CMD check flags $(wildcard) as a GNU make extension, so emit an explicit
# object list instead. Regenerated on every re-vendor.
{
  echo "## Generated by tools/vendor-cadical.sh -- do not edit by hand."
  echo "## Explicit object list: portable make has no \$(wildcard)."
  printf 'CADICAL_OBJECTS = \\\n'
  for f in "$DEST"/*.cpp "$DEST"/*.c; do
    b="$(basename "$f")"
    printf '  cadical/%s.o \\\n' "${b%.*}"
  done
  echo "  \$(NULL)"
} > "$DEST/objects.mk"

cat > "$DEST/VENDORED" <<EOT
CaDiCaL vendored from $REPO
version: $VERSION
ref:     $REF
commit:  $COMMIT
date:    $(date -u +%Y-%m-%d)

Regenerate with: tools/vendor-cadical.sh $REF
Local modifications: applied by tools/vendor/patch-for-r.sh, which reroutes
CaDiCaL's output and fatal paths to R's C API and compiles out the fork/exec
pipe code. See that script for what each rewrite does and why. The rest of
the build is configured via -D flags in src/Makevars.
EOT

# The vendor guard checks these two files: the manifest says what was
# fetched and from where, the checksums say the tree still matches it.
# Both are regenerated here so they can never drift from the actual copy.
if command -v sha256sum >/dev/null 2>&1; then SHA_SUM="sha256sum"
elif command -v shasum >/dev/null 2>&1; then SHA_SUM="shasum -a 256"
else echo "vendor: no sha256 tool found" >&2; exit 1; fi

MANIFEST="$PKG_ROOT/tools/vendor/manifest.tsv"
CHECKSUMS="$PKG_ROOT/tools/vendor/checksums.sha256"
mkdir -p "$PKG_ROOT/tools/vendor"

{
  printf 'name\trepo\tref\tcommit\tversion\tdest\n'
  printf 'cadical\t%s\t%s\t%s\t%s\t%s\n' \
    "$REPO" "$REF" "$COMMIT" "$VERSION" "src/cadical"
} > "$MANIFEST"

# Checksums are recorded over paths relative to the package root and sorted,
# so the file is reproducible regardless of where the script was run from.
( cd "$PKG_ROOT" && find src/cadical -type f \
    ! -name 'objects.mk' ! -name 'VENDORED' \
    | LC_ALL=C sort | xargs "$SHA_SUM" ) > "$CHECKSUMS"

echo "Vendored CaDiCaL $VERSION ($COMMIT) into src/cadical/"
echo "  $(ls "$DEST"/*.cpp | wc -l | tr -d ' ') .cpp, $(ls "$DEST"/*.c | wc -l | tr -d ' ') .c files"
