#!/bin/sh
# Vendor CaDiCaL into src/cadical/. Re-run to upgrade.
#
# Usage: tools/vendor-cadical.sh [git-ref]
set -eu

REF="${1:-rel-3.0.1}"
REPO="https://github.com/arminbiere/cadical.git"
PKG_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$PKG_ROOT/src/cadical"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "Cloning $REPO at $REF ..."
git clone --quiet --depth 1 --branch "$REF" "$REPO" "$TMP/cadical" 2>/dev/null \
  || { git clone --quiet "$REPO" "$TMP/cadical"; git -C "$TMP/cadical" checkout --quiet "$REF"; }

VERSION="$(cat "$TMP/cadical/VERSION")"
COMMIT="$(git -C "$TMP/cadical" rev-parse HEAD)"

rm -rf "$DEST"
mkdir -p "$DEST"
cp "$TMP"/cadical/src/*.cpp "$TMP"/cadical/src/*.hpp \
   "$TMP"/cadical/src/*.c   "$TMP"/cadical/src/*.h   "$DEST/"

# Drop files that define main() or export competing solver ABIs.
#   cadical.cpp / mobical.cpp -> main()
#   ipasir.cpp                -> IPASIR symbols we do not want in the .so
rm -f "$DEST/cadical.cpp" "$DEST/mobical.cpp" "$DEST/ipasir.cpp" "$DEST/ipasir.h"

cp "$TMP/cadical/LICENSE" "$PKG_ROOT/inst/CADICAL_LICENSE"

# ---------------------------------------------------------------- test corpus
# CaDiCaL's own regression instances, used by tests/testthat/test-corpus.R.
#
# Expected outcomes come from run.sh, which declares each as the solver's exit
# status: "run <name> 10" is satisfiable, 20 unsatisfiable. Do not infer them
# from whether a .sol file exists -- block0, elimredundant and sub0 are
# satisfiable feature tests that ship without one, and guessing that way
# reports three false failures.
#
# Instances are capped at 8KB each. That keeps 50 of the 85 in about 47KB and
# still covers every family -- adders, factoring, pigeonhole, elimination,
# subsumption, and the degenerate empty/false/unit cases -- while leaving out
# the large adders and prime factorisations that dominate both size and
# runtime.
CORPUS="$PKG_ROOT/inst/extdata/cadical"
CORPUS_MAX_BYTES=8192
RUN_SH="$TMP/cadical/test/cnf/run.sh"

[ -f "$RUN_SH" ] || die "cannot find test/cnf/run.sh in the upstream tree"

rm -rf "$CORPUS"
mkdir -p "$CORPUS"
printf 'name\texpected\n' > "$CORPUS/expected.tsv"

grep -oE '^[[:space:]]*run [a-zA-Z0-9_.-]+ [0-9]+' "$RUN_SH" |
  awk '{print $2, $3}' |
  while read -r name code; do
    src="$TMP/cadical/test/cnf/$name.cnf"
    [ -f "$src" ] || continue
    bytes=$(wc -c < "$src" | tr -d ' ')
    [ "$bytes" -le "$CORPUS_MAX_BYTES" ] || continue
    case "$code" in
      10) expected=sat;;
      20) expected=unsat;;
      *) continue;;
    esac
    cp "$src" "$CORPUS/$name.cnf"
    printf '%s\t%s\n' "$name" "$expected" >> "$CORPUS/expected.tsv"
  done


# Adapt the tree to R's C API (output, fatal paths, no fork/exec) before
# anything is recorded, so checksums cover exactly what gets compiled.
( cd "$PKG_ROOT" && ./tools/vendor/patch-for-r.sh )

# R CMD check flags $(wildcard) as a GNU make extension, so emit an explicit
# object list instead. Regenerated on every re-vendor.
{
  echo "## Generated by tools/vendor-cadical.sh -- do not edit by hand."
  echo "## Explicit object list: portable make has no \$(wildcard)."
  printf 'CADICAL_OBJECTS = \\\n'
  for f in "$DEST"/*.cpp "$DEST"/*.c; do
    b="$(basename "$f")"
    printf '  cadical/%s.o \\\n' "${b%.*}"
  done
  echo "  \$(NULL)"
} > "$DEST/objects.mk"

cat > "$DEST/VENDORED" <<EOT
CaDiCaL vendored from $REPO
version: $VERSION
ref:     $REF
commit:  $COMMIT

Regenerate with: tools/vendor-cadical.sh $REF

No date is recorded here on purpose. It would say when this script ran, which
is not a property of the vendored code -- the commit hash pins the upstream
state exactly, and ref and version say the rest. It was also the only thing
that made a re-vendor of the same ref look like a source change: the guard in
.github/workflows/vendor.yml counts everything under src/cadical/ as source,
so a no-op re-run demanded that manifest.tsv and checksums.sha256 be
regenerated to record nothing. Without it, re-running this script on the same
ref reproduces the tree byte for byte.
Local modifications: applied by tools/vendor/patch-for-r.sh, which reroutes
CaDiCaL's output and fatal paths to R's C API and compiles out the fork/exec
pipe code. See that script for what each rewrite does and why. The rest of
the build is configured via -D flags in src/Makevars.
EOT

# The vendor guard checks these two files: the manifest says what was
# fetched and from where, the checksums say the tree still matches it.
# Both are regenerated here so they can never drift from the actual copy.
if command -v sha256sum >/dev/null 2>&1; then SHA_SUM="sha256sum"
elif command -v shasum >/dev/null 2>&1; then SHA_SUM="shasum -a 256"
else echo "vendor: no sha256 tool found" >&2; exit 1; fi

MANIFEST="$PKG_ROOT/tools/vendor/manifest.tsv"
CHECKSUMS="$PKG_ROOT/tools/vendor/checksums.sha256"
mkdir -p "$PKG_ROOT/tools/vendor"

{
  printf 'name\trepo\tref\tcommit\tversion\tdest\n'
  printf 'cadical\t%s\t%s\t%s\t%s\t%s\n' \
    "$REPO" "$REF" "$COMMIT" "$VERSION" "src/cadical"
} > "$MANIFEST"

# Checksums are recorded over paths relative to the package root and sorted,
# so the file is reproducible regardless of where the script was run from.
( cd "$PKG_ROOT" && find src/cadical inst/extdata/cadical -type f \
    ! -name 'objects.mk' ! -name 'VENDORED' \
    | LC_ALL=C sort | xargs "$SHA_SUM" ) > "$CHECKSUMS"

echo "Vendored CaDiCaL $VERSION ($COMMIT) into src/cadical/"
echo "  $(ls "$DEST"/*.cpp | wc -l | tr -d ' ') .cpp, $(ls "$DEST"/*.c | wc -l | tr -d ' ') .c files"
